# Generated by Django 3.2.7 on 2022-05-27 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Odd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, max_length=200, null=True)),
                ('time', models.CharField(blank=True, max_length=200, null=True)),
                ('score', models.CharField(blank=True, max_length=200, null=True)),
                ('odd_1', models.CharField(blank=True, max_length=200, null=True)),
                ('odd_x', models.CharField(blank=True, max_length=200, null=True)),
                ('odd_2', models.CharField(blank=True, max_length=200, null=True)),
                ('odd_B', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
