# Generated by Django 3.2.7 on 2022-05-30 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customodds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='odd',
            old_name='odd_B',
            new_name='opening_odd',
        ),
        migrations.AddField(
            model_name='odd',
            name='payout',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
